export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';

export const FETCH_BYCOUNTRY_DATA_REQUEST = 'FETCH_BYCOUNTRY_DATA_REQUEST';
export const FETCH_BYCOUNTRY_DATA_SUCCESS = 'FETCH_BYCOUNTRY_DATA_SUCCESS';
export const FETCH_BYCOUNTRY_DATA_ERROR = 'FETCH_BYCOUNTRY_DATA_ERROR'; 

export const FETCH_ALLCOUNTRIES_REQUEST = 'FETCH_ALLCOUNTRIES_REQUEST';
export const FETCH_ALLCOUNTRIES_SUCCESS = 'FETCH_ALLCOUNTRIES_SUCCESS';
export const FETCH_ALLCOUNTRIES_ERROR = 'FETCH_ALLCOUNTRIES_ERROR';